apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher:view
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-configuration-watcher
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher
spec:
  selector:
    app: spring-cloud-kubernetes-configuration-watcher
  ports:
    - name: http
      port: 8888
      targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher
spec:
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-configuration-watcher
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
    spec:
      serviceAccount: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: spring-cloud-kubernetes-configuration-watcher
          image: springcloud/spring-cloud-kubernetes-configuration-watcher:2.0.3
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8888
              path: /actuator/health/liveness
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: spring-cloud-starter-kubernetes-demo
spec:
  type: NodePort
  selector:
    app: spring-cloud-starter-kubernetes-demo
  ports:
    - nodePort: 30808
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: spring-cloud-starter-kubernetes-demo
  labels:
    app: spring-cloud-starter-kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-starter-kubernetes-demo
  template:
    metadata:
      labels:
        app: spring-cloud-starter-kubernetes-demo
    spec:
      serviceAccount: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: spring-cloud-starter-kubernetes-demo
          image: microprograms/spring-cloud-starter-kubernetes-demo:1.0.2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: spring-cloud-starter-kubernetes-demo
data:
  application.yaml: |-
    management:
      endpoints:
        web:
          exposure:
            include: *
      endpoint:
        health:
          show-details: always
    demo:
      staticHostname: k8s-master-default-v1.0.2
      iconName: computer-vm
      chassis: vm
      machineId: 60943b8b8b72471c82b7e50337e0ab9e
      bootId: d5e57a99d1f64214a53f7954567ebf00
      virtualization: vmware
      operatingSystem: CentOS Linux 7 (Core)
      cpeOsName: cpe:/o:centos:centos:7
      kernel: Linux 4.4.220-1.el7.elrepo.x86_64
      architecture: x86-64

    ---
    spring:
      profiles: development
    demo:
      staticHostname: k8s-master-development
      iconName: computer-vm
      chassis: vm
      machineId: 60943b8b8b72471c82b7e50337e0ab9e
      bootId: d5e57a99d1f64214a53f7954567ebf00
      virtualization: vmware
      operatingSystem: CentOS Linux 7 (Core)
      cpeOsName: cpe:/o:centos:centos:7
      kernel: Linux 4.4.220-1.el7.elrepo.x86_64
      architecture: x86-64

    ---
    spring:
      profiles: production
    demo:
      staticHostname: k8s-master-production
      iconName: computer-vm
      chassis: vm
      machineId: 60943b8b8b72471c82b7e50337e0ab9e
      bootId: d5e57a99d1f64214a53f7954567ebf00
      virtualization: vmware
      operatingSystem: CentOS Linux 7 (Core)
      cpeOsName: cpe:/o:centos:centos:7
      kernel: Linux 4.4.220-1.el7.elrepo.x86_64
      architecture: x86-64
