apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.customizedName }}
  labels:
    app: {{ .Values.customizedName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.customizedName }}
  template:
    metadata:
      labels:
        app: {{ .Values.customizedName }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: {{ .Values.customizedName }}
          image: microprograms/spring-cloud-starter-kubernetes-demo:1.0.2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.customizedName }}
                  key: spring.profiles.active