apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: spring-cloud-starter-kubernetes-demo
  labels:
    app: spring-cloud-starter-kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-starter-kubernetes-demo
  template:
    metadata:
      labels:
        app: spring-cloud-starter-kubernetes-demo
    spec:
      serviceAccount: spring-cloud-kubernetes-configuration-watcher
      containers:
        - name: spring-cloud-starter-kubernetes-demo
          image: microprograms/spring-cloud-starter-kubernetes-demo:1.0.2
          ports:
            - containerPort: 8080
          env:
            # - name: SPRING_PROFILES_ACTIVE
            #   value: production
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-cloud-starter-kubernetes-demo
                  key: spring.profiles.active