apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-starter-kubernetes-demo
  labels:
    app: spring-cloud-starter-kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-starter-kubernetes-demo
  template:
    metadata:
      labels:
        app: spring-cloud-starter-kubernetes-demo
    spec:
      serviceAccount: spring-cloud-starter-kubernetes-demo
      containers:
        - name: spring-cloud-starter-kubernetes-demo
          image: microprograms/spring-cloud-starter-kubernetes-demo:2.0.12
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "256Mi"
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=100.0 -XX:InitialRAMPercentage=75.0
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-cloud-starter-kubernetes-demo
                  key: spring.profiles.active