apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-cloud-starter-kubernetes-demo
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-cloud-starter-kubernetes-demo
                port:
                  number: 80