apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: spring-cloud-starter-kubernetes-demo
spec:
  type: NodePort
  selector:
    app: spring-cloud-starter-kubernetes-demo
  ports:
    - nodePort: 30808
      port: 8080
      targetPort: 8080
