apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: spring-cloud-kubernetes-configuration-watcher:view
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-configuration-watcher
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
