apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-starter-kubernetes-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-cloud-starter-kubernetes-demo:namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-starter-kubernetes-demo:view
subjects:
  - kind: ServiceAccount
    name: spring-cloud-starter-kubernetes-demo
    apiGroup: ""
roleRef:
  kind: Role
  name: spring-cloud-starter-kubernetes-demo:namespace-reader
  apiGroup: ""
