apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.customizedName }}:namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount }}:view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.customizedName }}:namespace-reader
  apiGroup: ""
