apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.customizedName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.customizedName }}
  ports:
    - nodePort: 30808
      port: 8080
      targetPort: 8080
