apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-starter-kubernetes-demo
spec:
  type: NodePort
  selector:
    app: spring-cloud-starter-kubernetes-demo
  ports:
    - nodePort: {{ .Values.nodePort }}
      port: 8080
      targetPort: 8080
